# Generated by Django 6.0.2 on 2026-02-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("example_input", models.TextField(blank=True)),
                ("example_output", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("starter_code", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("code", models.TextField()),
                ("output", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="editor.codingquestion",
                    ),
                ),
            ],
        ),
    ]
